In [83]:
import numpy as np

# Create a 2x3 matrix

In [84]:

A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [4 5 6]]


In [85]:
# 3x3 Zero Matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:")
print(zero_matrix)

# 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Define two matrices of the same shape

In [86]:
B = np.array([[1, 2], [3, 4]])
C = np.array([[5, 6], [7, 8]])

# Matrix Addition
addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 6  8]
 [10 12]]
B - C:
[[-4 -4]
 [-4 -4]]


# Excersise 1

In [87]:
B = np.array([[5, 6], [8, 7]])
C = np.array([[2, 1], [4, 2]])


addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 7  7]
 [12  9]]
B - C:
[[3 5]
 [4 5]]


# Define matrices for multiplication

In [88]:
D = np.array([[1, 2], [3, 4]])
E = np.array([[2, 0], [1, 2]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)



D * E (Matrix Multiplication):
[[ 4  4]
 [10  8]]


# Excersise 2

In [89]:


# Define matrices for multiplication
D = np.array([[3, 7, 1], [2, 1,9]])
E = np.array([[5, 2], [1, 2],[6,4]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)



D * E (Matrix Multiplication):
[[28 24]
 [65 42]]


# Define matrices for multiplication

In [90]:
D = np.array([[3, 7, 1], [2, 1, 9]])
E = np.array([[5, 2, 1], [6, 4, 1]])  # Define E directly in the shape (2, 3)

# Element-wise Multiplication
elementwise_result = D * E
print("D * E (Element-wise Multiplication):")
print(elementwise_result)


D * E (Element-wise Multiplication):
[[15 14  1]
 [12  4  9]]


# Transpose of a Matrix

In [91]:
transpose_result = D.T
print("Transpose of D:")
print(transpose_result)

Transpose of D:
[[3 2]
 [7 1]
 [1 9]]


# Exercise 3: Matrix Transpose

In [92]:
d = np.array([[1, 2, 3], [4, 5, 6]])


transpose_matrix = d.T
print("Original Matrix (2x3):")
print(d)
print("\nTranspose of the Matrix (3x2):")
print(transpose_matrix)

Original Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Transpose of the Matrix (3x2):
[[1 4]
 [2 5]
 [3 6]]


# Define a 2x2 square matrix

In [93]:
F = np.array([[4, 2], [3, 1]])

# Determinant of F
determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)

Determinant of F: -2.0


# Exercise 4: Calculating the Determinant

In [94]:
F = np.array([[9, 8, 3], [2, 1, 6],[8,6,7]])

determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)


Determinant of F: 22.99999999999998


# Matrix Inverse

In [95]:
# Define an invertible 2x2 matrix
G = np.array([[4, 7], [2, 6]])

# Inverse of G
inverse_result = np.linalg.inv(G)
print("Inverse of G:")
print(inverse_result)

Inverse of G:
[[ 0.6 -0.7]
 [-0.2  0.4]]


# Exercise 5: Finding the Inverse

In [96]:
matrix = np.array([[4, 7, 2],
                   [3, 6, 1],
                   [2, 5, 9]])

# Calculate the inverse of the matrix
inverse_result = np.linalg.inv(matrix)

# Print the inverse
print("Inverse of the matrix:")
print(inverse_result)

Inverse of the matrix:
[[ 1.81481481 -1.96296296 -0.18518519]
 [-0.92592593  1.18518519  0.07407407]
 [ 0.11111111 -0.22222222  0.11111111]]


# Additional Challenge

In [97]:

A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]


result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]


for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]


print("Result of matrix multiplication:")
for row in result:
    print(row)


Result of matrix multiplication:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


## Generating a Random 10×1010 \times 1010×10 Matrix and Performing Basic Operations


In [98]:
# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)

Random 10x10 Matrix A:
[[0.00249031 0.64489764 0.25712193 0.7206846  0.39196723 0.4963367
  0.67589538 0.97276775 0.3109115  0.41586694]
 [0.65441373 0.61640438 0.47119245 0.77844786 0.5584328  0.02057692
  0.14175117 0.75588671 0.41505732 0.08806774]
 [0.86380123 0.64580624 0.98772294 0.56248539 0.97925358 0.16031105
  0.90113971 0.65602516 0.84406423 0.69182421]
 [0.83603065 0.30722168 0.78262745 0.07107799 0.49289838 0.55419564
  0.02977121 0.20869223 0.85164288 0.464792  ]
 [0.56588703 0.85899731 0.69209141 0.64725844 0.66588638 0.96151087
  0.22764456 0.50727352 0.28302064 0.5964041 ]
 [0.66433738 0.54847167 0.65094822 0.68171949 0.81826086 0.21856747
  0.0946858  0.08284787 0.53917261 0.95818769]
 [0.09898504 0.15953108 0.70599756 0.67825929 0.79160049 0.03699748
  0.65560987 0.66273053 0.64728534 0.05050018]
 [0.73675726 0.67030584 0.33454168 0.19169086 0.24199542 0.60885269
  0.26603163 0.05275723 0.77561443 0.85629481]
 [0.35355037 0.64581199 0.66888508 0.26279624 0.71895773 0

# Creating Another Random Matrix of the Same Size

# Generate a second random 10x10 matrix

In [99]:
random_matrix_B = np.random.rand(10, 10)
print("\nRandom 10x10 Matrix B:")
print(random_matrix_B)



Random 10x10 Matrix B:
[[0.58802582 0.11616256 0.79151882 0.70021819 0.62547617 0.9333832
  0.60871817 0.8058849  0.43655332 0.3429707 ]
 [0.37554653 0.599917   0.99243062 0.42446464 0.47194544 0.96456333
  0.7908959  0.80128576 0.64987344 0.79311671]
 [0.60240805 0.01530347 0.24896758 0.50774534 0.22490243 0.09099424
  0.15539372 0.54305713 0.61674309 0.47773029]
 [0.03022359 0.0151484  0.81562188 0.01422157 0.40309291 0.03459855
  0.15624217 0.14370212 0.63873917 0.5233398 ]
 [0.57724832 0.58606948 0.37315926 0.41571464 0.02810987 0.82701014
  0.36563044 0.39481399 0.93915921 0.27867864]
 [0.24812487 0.11474821 0.61103831 0.34662122 0.38710612 0.08833671
  0.88483817 0.21824935 0.04858774 0.94862129]
 [0.08614964 0.80255009 0.50337013 0.37555499 0.74994042 0.78997082
  0.84143715 0.21980603 0.31660025 0.99814462]
 [0.47402419 0.76903637 0.16163843 0.13149227 0.79705578 0.48195808
  0.36730409 0.14747195 0.45016711 0.41083808]
 [0.09527249 0.45674159 0.23667071 0.29003941 0.62228913 

# Matrix Addition

In [100]:

addition_result = random_matrix_A + random_matrix_B
print("\nA + B (Matrix Addition):")
print(addition_result)



A + B (Matrix Addition):
[[0.59051613 0.7610602  1.04864075 1.42090279 1.0174434  1.4297199
  1.28461356 1.77865265 0.74746482 0.75883764]
 [1.02996026 1.21632138 1.46362307 1.2029125  1.03037824 0.98514025
  0.93264707 1.55717247 1.06493076 0.88118444]
 [1.46620928 0.66110971 1.23669052 1.07023074 1.204156   0.25130529
  1.05653343 1.19908228 1.46080731 1.16955449]
 [0.86625424 0.32237008 1.59824932 0.08529956 0.89599128 0.5887942
  0.18601338 0.35239435 1.49038205 0.98813179]
 [1.14313535 1.44506679 1.06525068 1.06297307 0.69399626 1.788521
  0.593275   0.90208751 1.22217985 0.87508274]
 [0.91246226 0.66321988 1.26198654 1.02834071 1.20536698 0.30690418
  0.97952397 0.30109722 0.58776035 1.90680898]
 [0.18513468 0.96208118 1.20936769 1.05381428 1.54154091 0.8269683
  1.49704702 0.88253656 0.96388559 1.04864479]
 [1.21078145 1.43934222 0.49618012 0.32318313 1.0390512  1.09081077
  0.63333573 0.20022918 1.22578155 1.26713289]
 [0.44882286 1.10255358 0.90555579 0.55283565 1.34124686 1.

#  Matrix Subtraction

In [101]:

subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B (Matrix Subtraction):")
print(subtraction_result)



A - B (Matrix Subtraction):
[[-0.58553551  0.52873508 -0.53439689  0.0204664  -0.23350894 -0.43704651
   0.06717721  0.16688285 -0.12564181  0.07289624]
 [ 0.2788672   0.01648737 -0.52123817  0.35398322  0.08648736 -0.94398641
  -0.64914473 -0.04539905 -0.23481613 -0.70504897]
 [ 0.26139318  0.63050277  0.73875535  0.05474005  0.75435115  0.06931681
   0.74574599  0.11296803  0.22732114  0.21409392]
 [ 0.80580706  0.29207328 -0.03299443  0.05685641  0.08980547  0.51959709
  -0.12647096  0.06499011  0.2129037  -0.0585478 ]
 [-0.01136129  0.27292782  0.31893215  0.2315438   0.63777651  0.13450073
  -0.13798587  0.11245953 -0.65613857  0.31772546]
 [ 0.41621251  0.43372347  0.03990991  0.33509827  0.43115474  0.13023076
  -0.79015236 -0.13540148  0.49058488  0.0095664 ]
 [ 0.01283539 -0.64301901  0.20262743  0.30270429  0.04166007 -0.75297334
  -0.18582728  0.44292451  0.33068509 -0.94764444]
 [ 0.26273306 -0.09873053  0.17290325  0.06019858 -0.55506036  0.12689461
  -0.10127246 -0.09471

# Matrix Multiplication

In [102]:
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print("\nA * B (Matrix Multiplication):")
print(multiplication_result)


A * B (Matrix Multiplication):
[[1.40567447 2.37963448 2.57202568 1.50724415 2.73111594 2.47300859
  2.33009404 1.74767116 2.5892353  3.06836284]
 [1.67961905 1.7338152  2.4492302  1.54263671 2.19501219 2.6144169
  1.90368879 1.91245653 2.64463019 2.29243164]
 [2.58122519 3.14680751 3.68068048 2.99318057 3.76959165 4.39371678
  3.19841174 3.32409826 4.25807808 4.05621772]
 [1.78245296 1.50910121 2.28022665 2.11429669 2.2644314  2.65623122
  2.07878661 2.28258866 2.47199072 2.50729816]
 [2.12654583 2.17469007 3.46966564 2.37321525 2.88879295 2.97426857
  2.85101629 2.79822144 3.27250385 3.54478718]
 [1.83511023 1.91246042 3.00938592 2.31143156 2.5927909  2.87590727
  1.92489299 2.78951421 3.41809973 2.70107875]
 [1.47290516 1.95930432 1.90526047 1.40263642 2.07699051 2.41956221
  1.8357739  1.41599583 2.59475963 2.49293246]
 [1.48394055 1.84780657 2.806831   2.20132607 2.71591494 2.86480997
  2.32126815 2.54648247 2.55198454 2.89463699]
 [1.73778917 2.05177884 2.72019202 2.02799185 2.3

In [103]:
# Transpose of random_matrix_A
transpose_result_A = random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

# Transpose of random_matrix_B
transpose_result_B = random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.00249031 0.65441373 0.86380123 0.83603065 0.56588703 0.66433738
  0.09898504 0.73675726 0.35355037 0.31609138]
 [0.64489764 0.61640438 0.64580624 0.30722168 0.85899731 0.54847167
  0.15953108 0.67030584 0.64581199 0.00630056]
 [0.25712193 0.47119245 0.98772294 0.78262745 0.69209141 0.65094822
  0.70599756 0.33454168 0.66888508 0.08224785]
 [0.7206846  0.77844786 0.56248539 0.07107799 0.64725844 0.68171949
  0.67825929 0.19169086 0.26279624 0.93179729]
 [0.39196723 0.5584328  0.97925358 0.49289838 0.66588638 0.81826086
  0.79160049 0.24199542 0.71895773 0.61625673]
 [0.4963367  0.02057692 0.16031105 0.55419564 0.96151087 0.21856747
  0.03699748 0.60885269 0.92819469 0.05854078]
 [0.67589538 0.14175117 0.90113971 0.02977121 0.22764456 0.0946858
  0.65560987 0.26603163 0.65517726 0.95432589]
 [0.97276775 0.75588671 0.65602516 0.20869223 0.50727352 0.08284787
  0.66273053 0.05275723 0.18060731 0.90651198]
 [0.3109115  0.41505732 0.84406423 0.85164288 0.28302064 

# Learning Assessment Questions

# 1. Matrix Creation and Structure


A matrix is a grid of numbers, symbols, or expressions organized into rows and columns. It's a fundamental tool in linear algebra, used in various fields like physics, computer graphics, and machine learning. The size of a matrix is determined by the number of rows and columns it contains.

Sample Code Below:

In [104]:

k_3x23 = np.random.randint(1, 10,(3, 23))


k_23x2 = np.random.randint(1, 10,(23, 2))

print("3x23 Matrix:\n", k_3x23)
print("\n23x2 Matrix:\n", k_23x2)


3x23 Matrix:
 [[6 9 4 8 3 4 4 5 4 1 9 9 2 6 7 3 5 5 8 4 9 8 1]
 [1 1 6 5 8 1 9 2 3 7 6 3 8 6 3 3 5 3 5 9 2 9 1]
 [3 2 5 4 1 3 3 5 7 9 3 9 5 9 1 2 9 8 1 9 2 9 8]]

23x2 Matrix:
 [[4 7]
 [2 3]
 [6 6]
 [9 6]
 [9 6]
 [7 4]
 [3 1]
 [9 6]
 [6 4]
 [8 4]
 [4 9]
 [6 1]
 [7 1]
 [1 5]
 [7 6]
 [9 8]
 [9 3]
 [1 7]
 [1 4]
 [8 1]
 [7 5]
 [2 1]
 [3 1]]


# 2. Basic Matrix Operations
To add matrices, they must have the same shape meaning the same number of rows and columns. You add corresponding elements to get the resulting matrix.

To multiply matrices, the number of columns in the first matrix must equal the number of rows in the second. The result will have the same number of rows as the first and the same number of columns as the second. Each element in the result is calculated by multiplying corresponding elements in a row of the first matrix with corresponding elements in a column of the second matrix, and then summing these products.lt is a dot product of a row from the first matrix and a column from the second.

Sample Code:

In [105]:


A = np.random.randint(1, 10,(5, 5))
B = np.random.randint(1, 10,(5, 5))


matrix_sum = A + B


matrix_product = np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix Addition (A + B):\n", matrix_sum)
print("\nMatrix Multiplication (A * B):\n", matrix_product)


Matrix A:
 [[2 4 8 2 4]
 [5 7 7 2 8]
 [8 6 5 3 6]
 [5 5 7 9 8]
 [3 7 9 9 7]]

Matrix B:
 [[7 1 3 8 6]
 [4 6 8 1 6]
 [7 8 6 4 6]
 [4 1 8 8 8]
 [7 1 7 8 8]]

Matrix Addition (A + B):
 [[ 9  5 11 10 10]
 [ 9 13 15  3 14]
 [15 14 11  7 12]
 [ 9  6 15 17 16]
 [10  8 16 17 15]]

Matrix Multiplication (A * B):
 [[122  96 130 100 132]
 [176 113 185 155 194]
 [169  93 168 162 186]
 [196 108 225 209 238]
 [197 133 240 195 242]]


# 3. Matrix Transposition
The transpose of a matrix is created by interchanging its rows and columns. If a matrix is 𝑚 × 𝑛, its transpose will be 𝑛 × 𝑚.

Sample Code:


In [106]:

k = np.random.randint(1, 10, (3, 2))


matrix_transpose = k.T

print("Original 3x2 Matrix:\n", matrix)
print("\nTranspose of the Matrix (2x3):\n", matrix_transpose)

Original 3x2 Matrix:
 [[4 7 2]
 [3 6 1]
 [2 5 9]]

Transpose of the Matrix (2x3):
 [[6 3 5]
 [8 7 5]]


# 4. Working with Large Matrices

In [107]:
matrix = np.random.randint(1, 11, (5, 5))

matrix_sum = np.sum(matrix)


matrix_transpose = matrix.T

# Print the results
print("Original 5x5 Matrix:\n", matrix)
print("\nSum of all elements in the matrix:", matrix_sum)
print("\nTranspose of the Matrix:\n", matrix_transpose)

Original 5x5 Matrix:
 [[ 2  3  5  1  8]
 [ 6  2  3  3  4]
 [ 1  3  5  4  6]
 [ 7  2  9 10  3]
 [ 7  8  9  6  3]]

Sum of all elements in the matrix: 120

Transpose of the Matrix:
 [[ 2  6  1  7  7]
 [ 3  2  3  2  8]
 [ 5  3  5  9  9]
 [ 1  3  4 10  6]
 [ 8  4  6  3  3]]


# Answer:
To generate a 5x5 matrix with random integers between 1 and 10 in NumPy, we can use np.random.randint(1, 11, (5, 5)). To calculate the sum of all elements, we use np.sum(matrix). To find the transpose, we use matrix.T, which switches rows and columns. This gives us both the total sum and the transposed matrix.






# Applying Matrix Operations in Context

Matrix Addition  (D+E), we add corresponding elements. This is useful for combining information, like merging images or increasing brightness.

Matrix Subtraction  (D-E), we find the difference between corresponding elements. This helps identify changes, such as movement in images or video frames.

Matrix Multiplication  (D*E), we combine them in a specific way. This is crucial for tasks like rotating objects in graphics and complex calculations in machine learning.

In [108]:

D = np.random.randint(1, 11, (10, 10))
E = np.random.randint(1, 11, (10, 10))


matrix_addition = D + E
print("Matrix Addition (D + E):\n", matrix_addition)


matrix_subtraction = D - E
print("\nMatrix Subtraction (D - E):\n", matrix_subtraction)


matrix_multiplication = np.dot(D, E)
print("\nMatrix Multiplication (D * E):\n", matrix_multiplication)


Matrix Addition (D + E):
 [[12 10 11 13 18 10  9 20  4 12]
 [ 6 13  7  5  7 12  7  4  6 10]
 [15 20 12 17 13 15 13  9 14 14]
 [13  4  9 11 12  5  7 13 12  4]
 [13  3 10 15  9 13 17  7  8 17]
 [13 16  7  9  9 14 10  9  7  5]
 [ 2 12  9  9 14  8 15 11  9 15]
 [ 7  6 15  8 12 19  9  5  4  8]
 [19  9  4 14 10 10  9 16 14 10]
 [11  6 11  8  8 11 18 13  8 17]]

Matrix Subtraction (D - E):
 [[ 6  8  7  5  0  8  5  0  2  8]
 [ 2 -5  1  1 -5 -2  3  0  0  8]
 [-1  0  2 -1  5 -3 -7 -1  4  2]
 [-5  0  7  1 -8  3 -5  3  8  0]
 [ 1  1  2  3 -5  5  1  3 -2  3]
 [-7  0  1  7  1 -4 -6  3 -1  1]
 [ 0 -8  3 -7  6 -4 -5  5 -1 -1]
 [ 1  2 -5  0  4 -1  5 -3 -2  4]
 [ 1 -1 -2 -6 -2 -2 -3  2  0 -2]
 [-1  4  3 -6 -4 -9  2  5 -4 -3]]

Matrix Multiplication (D * E):
 [[466 394 332 439 506 539 512 365 326 374]
 [227 205 142 227 233 278 266 180 173 211]
 [427 331 249 397 448 430 428 321 295 323]
 [313 226 201 292 278 306 278 243 199 196]
 [367 302 220 344 373 395 418 288 248 302]
 [274 226 180 230 294 288 264 194 